### ISSUE TITLE
Unable to click on Menu Item when the disabled property is set via a call back function

### ISSUE THREAD

**Issue by umasiyer** [fkhadra/react-contexify#55]
Hi,
We are trying to use react-contexify inside a table element. The table is formed using the package react-table. 
We have a couple of scenarios which we wanted the context menu to fulfill:
1. Have dynamic rendering of the menu with enabled and disabled menu items
2. Each enabled item should have a click handler. 

In the below-mentioned sandbox environment, we are able to get the dynamic disabling of the menu items. But once that is established, the menu item is not clickable. 
**Note: If we try setting disabled={false}, the click action is triggered.** 
Sandbox Link: https://codesandbox.io/s/01yn11wkq0

**Comment by fkhadra** [comment]
Hello @umasiyer,

The bug has been fixed 😆. Sorry for the trouble

**Comment by umasiyer** [comment]
@fkhadra , Thank you, I will update the changes and let you know if anything still persists!
Thank you for the quick turnaround!

**Comment by umasiyer** [comment]
Thank you!!! Verified :+1:

**Comment by fkhadra** [comment]
You're welcome !
